import type { PlaceDesk } from "./types";

/** Compact AHJ factory. Confirm portal/edition with the department before applying. */
export function p(
  id: string,
  name: string,
  kind: PlaceDesk["kind"],
  state: string,
  ahjName: string,
  portalName: string,
  url: string,
  county?: string,
  note?: string,
): PlaceDesk {
  return {
    id,
    name,
    kind,
    state,
    county,
    ahjName,
    portalName,
    portalUrl: url,
    departmentUrl: url,
    notes: note ? [note] : ["Confirm city vs county jurisdiction at the parcel before you apply."],
    extraLinks: [],
  };
}

/**
 * Additional named AHJs — no overlap with CORE_PLACES ids.
 * Official department / permitting landing pages. Guidance only.
 */
export const EXTRA_PLACES: PlaceDesk[] = [
  // Alabama
  p("al-montgomery", "Montgomery", "city", "AL", "Montgomery Land Development / Permits", "City permitting", "https://www.montgomeryal.gov/", "Montgomery"),
  p("al-huntsville", "Huntsville", "city", "AL", "Huntsville Planning / Inspection", "City permitting", "https://www.huntsvilleal.gov/development/", "Madison"),
  p("al-mobile", "Mobile", "city", "AL", "Mobile Urban Development", "City permitting", "https://www.cityofmobile.org/", "Mobile"),
  p("al-tuscaloosa", "Tuscaloosa", "city", "AL", "Tuscaloosa Planning & Development Services", "City permitting", "https://www.tuscaloosa.com/", "Tuscaloosa"),
  p("al-hoover", "Hoover", "city", "AL", "Hoover Inspection Services", "City permitting", "https://www.hooveralabama.gov/", "Jefferson"),
  p("al-madison", "Madison", "city", "AL", "Madison Building Department", "City permitting", "https://www.madisonal.gov/", "Madison"),
  p("al-auburn", "Auburn", "city", "AL", "Auburn Inspection Services", "City permitting", "https://www.auburnalabama.org/", "Lee"),
  // Alaska
  p("ak-fairbanks", "Fairbanks", "city", "AK", "Fairbanks Building Department", "City permitting", "https://www.fairbanksalaska.us/", "Fairbanks North Star"),
  p("ak-juneau", "Juneau", "city", "AK", "Juneau Community Development", "City permitting", "https://juneau.org/community-development", "Juneau"),
  p("ak-matsu", "Matanuska-Susitna Borough", "county", "AK", "Mat-Su Borough Permit Center", "Borough permits", "https://www.matsugov.us/"),
  // Arizona
  p("az-mesa", "Mesa", "city", "AZ", "Mesa Development Services", "City permitting", "https://www.mesaaz.gov/business/development-services", "Maricopa"),
  p("az-chandler", "Chandler", "city", "AZ", "Chandler Development Services", "City permitting", "https://www.chandleraz.gov/government/departments/development-services", "Maricopa"),
  p("az-scottsdale", "Scottsdale", "city", "AZ", "Scottsdale Planning & Development", "City permitting", "https://www.scottsdaleaz.gov/planning-development", "Maricopa"),
  p("az-gilbert", "Gilbert", "city", "AZ", "Gilbert Development Services", "City permitting", "https://www.gilbertaz.gov/departments/development-services", "Maricopa"),
  p("az-glendale", "Glendale", "city", "AZ", "Glendale Development Services", "City permitting", "https://www.glendaleaz.com/live/city_services/development_services", "Maricopa"),
  p("az-tempe", "Tempe", "city", "AZ", "Tempe Community Development", "City permitting", "https://www.tempe.gov/government/community-development", "Maricopa"),
  p("az-peoria", "Peoria", "city", "AZ", "Peoria Development & Engineering", "City permitting", "https://www.peoriaaz.gov/", "Maricopa"),
  p("az-surprise", "Surprise", "city", "AZ", "Surprise Community Development", "City permitting", "https://www.surpriseaz.gov/", "Maricopa"),
  p("az-yuma", "Yuma", "city", "AZ", "Yuma Community Development", "City permitting", "https://www.yumaaz.gov/", "Yuma"),
  p("az-flagstaff", "Flagstaff", "city", "AZ", "Flagstaff Community Development", "City permitting", "https://www.flagstaff.az.gov/", "Coconino"),
  p("az-maricopa-county", "Maricopa County", "county", "AZ", "Maricopa County Planning & Development", "County P&D", "https://www.maricopa.gov/164/Planning-Development", undefined, "Unincorporated county is a different AHJ from Phoenix, Mesa, and other cities."),
  p("az-pima-county", "Pima County", "county", "AZ", "Pima County Development Services", "County DSD", "https://webcms.pima.gov/cms/one.aspx?pageId=3492"),
  // Arkansas
  p("ar-fayetteville", "Fayetteville", "city", "AR", "Fayetteville Development Services", "City permitting", "https://www.fayetteville-ar.gov/", "Washington"),
  p("ar-fort-smith", "Fort Smith", "city", "AR", "Fort Smith Planning & Zoning", "City permitting", "https://www.fortsmithar.gov/", "Sebastian"),
  p("ar-springdale", "Springdale", "city", "AR", "Springdale Planning & Community Development", "City permitting", "https://www.springdalear.gov/", "Washington"),
  p("ar-jonesboro", "Jonesboro", "city", "AR", "Jonesboro Inspection Department", "City permitting", "https://www.jonesboro.org/", "Craighead"),
  p("ar-rogers", "Rogers", "city", "AR", "Rogers Community Development", "City permitting", "https://www.rogersar.gov/", "Benton"),
  p("ar-conway", "Conway", "city", "AR", "Conway Planning & Development", "City permitting", "https://www.conwayarkansas.gov/", "Faulkner"),
  p("ar-north-little-rock", "North Little Rock", "city", "AR", "NLR Planning", "City permitting", "https://www.nlr.ar.gov/", "Pulaski"),
  // California — large remaining cities + counties
  p("ca-long-beach", "Long Beach", "city", "CA", "Long Beach Development Services", "City permitting", "https://www.longbeach.gov/lbds/", "Los Angeles"),
  p("ca-fresno", "Fresno", "city", "CA", "Fresno Planning & Development", "City permitting", "https://www.fresno.gov/darm/", "Fresno"),
  p("ca-bakersfield", "Bakersfield", "city", "CA", "Bakersfield Development Services", "City permitting", "https://www.bakersfieldcity.us/", "Kern"),
  p("ca-anaheim", "Anaheim", "city", "CA", "Anaheim Planning & Building", "City permitting", "https://www.anaheim.net/597/Planning-Building", "Orange"),
  p("ca-santa-ana", "Santa Ana", "city", "CA", "Santa Ana Planning & Building", "City permitting", "https://www.santa-ana.org/", "Orange"),
  p("ca-riverside", "Riverside", "city", "CA", "Riverside Community Development", "City permitting", "https://riversideca.gov/building", "Riverside"),
  p("ca-irvine", "Irvine", "city", "CA", "Irvine Community Development", "City permitting", "https://www.cityofirvine.org/community-development", "Orange"),
  p("ca-stockton", "Stockton", "city", "CA", "Stockton Community Development", "City permitting", "https://www.stocktonca.gov/", "San Joaquin"),
  p("ca-chula-vista", "Chula Vista", "city", "CA", "Chula Vista Development Services", "City permitting", "https://www.chulavistaca.gov/", "San Diego"),
  p("ca-fremont", "Fremont", "city", "CA", "Fremont Community Development", "City permitting", "https://www.fremont.gov/", "Alameda"),
  p("ca-santa-clarita", "Santa Clarita", "city", "CA", "Santa Clarita Community Development", "City permitting", "https://www.santa-clarita.com/", "Los Angeles"),
  p("ca-san-bernardino", "San Bernardino", "city", "CA", "San Bernardino Community Development", "City permitting", "https://www.sbcity.org/", "San Bernardino"),
  p("ca-modesto", "Modesto", "city", "CA", "Modesto Community Development", "City permitting", "https://www.modestogov.com/", "Stanislaus"),
  p("ca-fontana", "Fontana", "city", "CA", "Fontana Community Development", "City permitting", "https://www.fontanaca.gov/", "San Bernardino"),
  p("ca-oxnard", "Oxnard", "city", "CA", "Oxnard Development Services", "City permitting", "https://www.oxnard.gov/", "Ventura"),
  p("ca-huntington-beach", "Huntington Beach", "city", "CA", "Huntington Beach Community Development", "City permitting", "https://www.huntingtonbeachca.gov/", "Orange"),
  p("ca-glendale", "Glendale", "city", "CA", "Glendale Community Development", "City permitting", "https://www.glendaleca.gov/", "Los Angeles"),
  p("ca-moreno-valley", "Moreno Valley", "city", "CA", "Moreno Valley Community Development", "City permitting", "https://www.moval.org/", "Riverside"),
  p("ca-santa-rosa", "Santa Rosa", "city", "CA", "Santa Rosa Planning & Economic Development", "City permitting", "https://www.srcity.org/", "Sonoma"),
  p("ca-ontario", "Ontario", "city", "CA", "Ontario Planning / Building", "City permitting", "https://www.ontarioca.gov/", "San Bernardino"),
  p("ca-elk-grove", "Elk Grove", "city", "CA", "Elk Grove Development Services", "City permitting", "https://www.elkgrovecity.org/", "Sacramento"),
  p("ca-rancho-cucamonga", "Rancho Cucamonga", "city", "CA", "Rancho Cucamonga Planning", "City permitting", "https://www.cityofrc.us/", "San Bernardino"),
  p("ca-oceanside", "Oceanside", "city", "CA", "Oceanside Development Services", "City permitting", "https://www.ci.oceanside.ca.us/", "San Diego"),
  p("ca-garden-grove", "Garden Grove", "city", "CA", "Garden Grove Community Development", "City permitting", "https://ggcity.org/", "Orange"),
  p("ca-lancaster", "Lancaster", "city", "CA", "Lancaster Community Development", "City permitting", "https://www.cityoflancasterca.org/", "Los Angeles"),
  p("ca-palmdale", "Palmdale", "city", "CA", "Palmdale Building & Safety", "City permitting", "https://www.cityofpalmdale.org/", "Los Angeles"),
  p("ca-hayward", "Hayward", "city", "CA", "Hayward Development Services", "City permitting", "https://www.hayward-ca.gov/", "Alameda"),
  p("ca-salinas", "Salinas", "city", "CA", "Salinas Community Development", "City permitting", "https://www.cityofsalinas.org/", "Monterey"),
  p("ca-sunnyvale", "Sunnyvale", "city", "CA", "Sunnyvale Community Development", "City permitting", "https://www.sunnyvale.ca.gov/", "Santa Clara"),
  p("ca-pasadena", "Pasadena", "city", "CA", "Pasadena Planning & Community Development", "City permitting", "https://www.cityofpasadena.net/", "Los Angeles"),
  p("ca-orange", "Orange", "city", "CA", "Orange Community Development", "City permitting", "https://www.cityoforange.org/", "Orange"),
  p("ca-fullerton", "Fullerton", "city", "CA", "Fullerton Community Development", "City permitting", "https://www.cityoffullerton.com/", "Orange"),
  p("ca-thousand-oaks", "Thousand Oaks", "city", "CA", "Thousand Oaks Building Division", "City permitting", "https://toaks.gov/building", "Ventura"),
  p("ca-visalia", "Visalia", "city", "CA", "Visalia Community Development", "City permitting", "https://www.visalia.city/", "Tulare"),
  p("ca-concord", "Concord", "city", "CA", "Concord Community Development", "City permitting", "https://www.cityofconcord.org/", "Contra Costa"),
  p("ca-roseville", "Roseville", "city", "CA", "Roseville Development Services", "City permitting", "https://www.roseville.ca.us/", "Placer"),
  p("ca-berkeley", "Berkeley", "city", "CA", "Berkeley Planning & Development", "City permitting", "https://berkeleyca.gov/", "Alameda"),
  p("ca-torrance", "Torrance", "city", "CA", "Torrance Community Development", "City permitting", "https://www.torranceca.gov/", "Los Angeles"),
  p("ca-ventura", "Ventura", "city", "CA", "Ventura Community Development", "City permitting", "https://www.cityofventura.ca.gov/", "Ventura"),
  p("ca-carlsbad", "Carlsbad", "city", "CA", "Carlsbad Community Development", "City permitting", "https://www.carlsbadca.gov/", "San Diego"),
  p("ca-temecula", "Temecula", "city", "CA", "Temecula Community Development", "City permitting", "https://temeculaca.gov/", "Riverside"),
  p("ca-costa-mesa", "Costa Mesa", "city", "CA", "Costa Mesa Development Services", "City permitting", "https://www.costamesaca.gov/", "Orange"),
  p("ca-santa-monica", "Santa Monica", "city", "CA", "Santa Monica Community Development", "City permitting", "https://www.santamonica.gov/", "Los Angeles"),
  p("ca-burbank", "Burbank", "city", "CA", "Burbank Community Development", "City permitting", "https://www.burbankca.gov/", "Los Angeles"),
  p("ca-palo-alto", "Palo Alto", "city", "CA", "Palo Alto Development Services", "City permitting", "https://www.cityofpaloalto.org/", "Santa Clara"),
  p("ca-mountain-view", "Mountain View", "city", "CA", "Mountain View Community Development", "City permitting", "https://www.mountainview.gov/", "Santa Clara"),
  p("ca-los-angeles-county", "Los Angeles County", "county", "CA", "LA County Public Works Building & Safety", "County BSD", "https://pw.lacounty.gov/bsd/", undefined, "Unincorporated county — not LADBS."),
  p("ca-orange-county", "Orange County", "county", "CA", "OC Public Works / Building", "County building", "https://ocpw.ocgov.com/"),
  p("ca-san-diego-county", "San Diego County", "county", "CA", "County PDS Building Division", "County PDS", "https://www.sandiegocounty.gov/pds/"),
  p("ca-riverside-county", "Riverside County", "county", "CA", "Riverside County Building & Safety", "County building", "https://rctlma.org/building"),
  p("ca-san-bernardino-county", "San Bernardino County", "county", "CA", "County Land Use Services", "County LUS", "https://lus.sbcounty.gov/"),
  p("ca-alameda-county", "Alameda County", "county", "CA", "Alameda County Planning / Building", "County building", "https://www.acgov.org/cda/planning/"),
  p("ca-sacramento-county", "Sacramento County", "county", "CA", "Sacramento County Building Permits", "County building", "https://building.saccounty.gov/"),
  p("ca-contra-costa-county", "Contra Costa County", "county", "CA", "Contra Costa Department of Conservation & Development", "County DCD", "https://www.contracosta.ca.gov/"),
  // Colorado
  p("co-colorado-springs", "Colorado Springs", "city", "CO", "Colorado Springs Land Use Review", "City permitting", "https://coloradosprings.gov/", "El Paso"),
  p("co-aurora", "Aurora", "city", "CO", "Aurora Planning & Development Services", "City permitting", "https://www.auroragov.org/", "Arapahoe"),
  p("co-fort-collins", "Fort Collins", "city", "CO", "Fort Collins Community Development & Neighborhood Services", "City permitting", "https://www.fcgov.com/", "Larimer"),
  p("co-lakewood", "Lakewood", "city", "CO", "Lakewood Planning / Permits", "City permitting", "https://www.lakewood.org/", "Jefferson"),
  p("co-thornton", "Thornton", "city", "CO", "Thornton City Development", "City permitting", "https://www.thorntonco.gov/", "Adams"),
  p("co-arvada", "Arvada", "city", "CO", "Arvada Community Development", "City permitting", "https://arvada.org/", "Jefferson"),
  p("co-westminster", "Westminster", "city", "CO", "Westminster Community Development", "City permitting", "https://www.cityofwestminster.us/", "Adams"),
  p("co-pueblo", "Pueblo", "city", "CO", "Pueblo Planning & Community Development", "City permitting", "https://www.pueblo.us/", "Pueblo"),
  p("co-boulder", "Boulder", "city", "CO", "Boulder Planning & Development Services", "City permitting", "https://bouldercolorado.gov/", "Boulder"),
  p("co-greeley", "Greeley", "city", "CO", "Greeley Community Development", "City permitting", "https://greeleygov.com/", "Weld"),
  p("co-centennial", "Centennial", "city", "CO", "Centennial Community Development", "City permitting", "https://www.centennialco.gov/", "Arapahoe"),
  // Connecticut
  p("ct-new-haven", "New Haven", "city", "CT", "New Haven Building Department", "City building", "https://www.newhavenct.gov/", "New Haven"),
  p("ct-stamford", "Stamford", "city", "CT", "Stamford Land Use / Building", "City permitting", "https://www.stamfordct.gov/", "Fairfield"),
  p("ct-bridgeport", "Bridgeport", "city", "CT", "Bridgeport Building Department", "City building", "https://www.bridgeportct.gov/", "Fairfield"),
  p("ct-waterbury", "Waterbury", "city", "CT", "Waterbury Building Department", "City building", "https://www.waterburyct.org/", "New Haven"),
  p("ct-norwalk", "Norwalk", "city", "CT", "Norwalk Building Department", "City building", "https://www.norwalkct.gov/", "Fairfield"),
  p("ct-danbury", "Danbury", "city", "CT", "Danbury Permit Center", "City permitting", "https://www.danbury-ct.gov/", "Fairfield"),
  p("ct-new-britain", "New Britain", "city", "CT", "New Britain Building Department", "City building", "https://www.newbritainct.gov/", "Hartford"),
  // Delaware
  p("de-dover", "Dover", "city", "DE", "Dover Planning / Inspections", "City permitting", "https://www.cityofdover.com/", "Kent"),
  p("de-newark", "Newark", "city", "DE", "Newark Planning & Development", "City permitting", "https://newarkde.gov/", "New Castle"),
  p("de-new-castle-county", "New Castle County", "county", "DE", "NCC Land Use", "County land use", "https://www.newcastlede.gov/"),
  // Florida — remaining large cities + counties
  p("fl-tallahassee", "Tallahassee", "city", "FL", "Tallahassee Growth Management", "City permitting", "https://www.talgov.com/", "Leon"),
  p("fl-gainesville", "Gainesville", "city", "FL", "Gainesville Building Inspection", "City permitting", "https://www.gainesvillefl.gov/", "Alachua"),
  p("fl-cape-coral", "Cape Coral", "city", "FL", "Cape Coral Development Services", "City permitting", "https://www.capecoral.gov/", "Lee"),
  p("fl-port-st-lucie", "Port St. Lucie", "city", "FL", "Port St. Lucie Building Department", "City permitting", "https://www.cityofpsl.com/", "St. Lucie"),
  p("fl-pembroke-pines", "Pembroke Pines", "city", "FL", "Pembroke Pines Building", "City permitting", "https://www.ppines.com/", "Broward"),
  p("fl-hollywood", "Hollywood", "city", "FL", "Hollywood Building Division", "City permitting", "https://www.hollywoodfl.org/", "Broward"),
  p("fl-miramar", "Miramar", "city", "FL", "Miramar Community Development", "City permitting", "https://www.miramarfl.gov/", "Broward"),
  p("fl-coral-springs", "Coral Springs", "city", "FL", "Coral Springs Building Division", "City permitting", "https://www.coralsprings.gov/", "Broward"),
  p("fl-clearwater", "Clearwater", "city", "FL", "Clearwater Building / Planning", "City permitting", "https://www.myclearwater.com/", "Pinellas"),
  p("fl-palm-bay", "Palm Bay", "city", "FL", "Palm Bay Building Division", "City permitting", "https://www.palmbayflorida.org/", "Brevard"),
  p("fl-pompano-beach", "Pompano Beach", "city", "FL", "Pompano Beach Building Inspections", "City permitting", "https://www.pompanobeachfl.gov/", "Broward"),
  p("fl-lakeland", "Lakeland", "city", "FL", "Lakeland Building Inspection", "City permitting", "https://www.lakelandgov.net/", "Polk"),
  p("fl-davie", "Davie", "city", "FL", "Davie Building Division", "City permitting", "https://www.davie-fl.gov/", "Broward"),
  p("fl-boca-raton", "Boca Raton", "city", "FL", "Boca Raton Development Services", "City permitting", "https://www.myboca.us/", "Palm Beach"),
  p("fl-fort-myers", "Fort Myers", "city", "FL", "Fort Myers Community Development", "City permitting", "https://www.fortmyers.gov/", "Lee"),
  p("fl-melbourne", "Melbourne", "city", "FL", "Melbourne Building Division", "City permitting", "https://www.melbourneflorida.org/", "Brevard"),
  p("fl-kissimmee", "Kissimmee", "city", "FL", "Kissimmee Development Services", "City permitting", "https://www.kissimmee.gov/", "Osceola"),
  p("fl-homestead", "Homestead", "city", "FL", "Homestead Building Department", "City permitting", "https://www.homesteadfl.gov/", "Miami-Dade"),
  p("fl-doral", "Doral", "city", "FL", "Doral Building Department", "City permitting", "https://www.cityofdoral.com/", "Miami-Dade"),
  p("fl-daytona-beach", "Daytona Beach", "city", "FL", "Daytona Beach Building Division", "City permitting", "https://www.codb.us/", "Volusia"),
  p("fl-sarasota", "Sarasota", "city", "FL", "Sarasota Development Services", "City permitting", "https://www.sarasotafl.gov/", "Sarasota"),
  p("fl-pensacola", "Pensacola", "city", "FL", "Pensacola Inspection Services", "City permitting", "https://www.cityofpensacola.com/", "Escambia"),
  p("fl-broward-county", "Broward County", "county", "FL", "Broward County Building Division", "County building", "https://www.broward.org/Building/Pages/Default.aspx", undefined, "Unincorporated Broward and some contract cities. Fort Lauderdale is a separate AHJ."),
  p("fl-hillsborough-county", "Hillsborough County", "county", "FL", "Hillsborough Development Services", "County permitting", "https://www.hillsboroughcounty.org/"),
  p("fl-orange-county", "Orange County", "county", "FL", "Orange County Building Safety", "County building", "https://www.orangecountyfl.net/PermitsLicenses.aspx", undefined, "Unincorporated Orange. Orlando is a separate AHJ."),
  p("fl-pinellas-county", "Pinellas County", "county", "FL", "Pinellas Building Services", "County building", "https://pinellas.gov/"),
  p("fl-lee-county", "Lee County", "county", "FL", "Lee County Community Development", "County permitting", "https://www.leegov.com/dcd"),
  p("fl-polk-county", "Polk County", "county", "FL", "Polk County Building Division", "County building", "https://www.polk-county.net/"),
  p("fl-volusia-county", "Volusia County", "county", "FL", "Volusia Building & Zoning", "County building", "https://www.volusia.org/"),
  p("fl-brevard-county", "Brevard County", "county", "FL", "Brevard Permitting & Enforcement", "County permitting", "https://www.brevardfl.gov/"),
  p("fl-collier-county", "Collier County", "county", "FL", "Collier Growth Management", "County permitting", "https://www.colliercountyfl.gov/"),
  p("fl-seminole-county", "Seminole County", "county", "FL", "Seminole Building Division", "County building", "https://www.seminolecountyfl.gov/"),
  // Georgia
  p("ga-augusta", "Augusta", "city", "GA", "Augusta Planning & Development", "City/county permitting", "https://www.augustaga.gov/", "Richmond", "Consolidated Augusta-Richmond."),
  p("ga-columbus", "Columbus", "city", "GA", "Columbus Consolidated Government Inspections", "City permitting", "https://www.columbusga.gov/", "Muscogee"),
  p("ga-savannah", "Savannah", "city", "GA", "Savannah Development Services", "City permitting", "https://www.savannahga.gov/", "Chatham"),
  p("ga-athens", "Athens", "city", "GA", "Athens-Clarke Building Inspections", "Unified government", "https://www.accgov.com/", "Clarke"),
  p("ga-macon", "Macon", "city", "GA", "Macon-Bibb Business Development Services", "City/county permitting", "https://www.maconbibb.us/", "Bibb"),
  p("ga-sandy-springs", "Sandy Springs", "city", "GA", "Sandy Springs Community Development", "City permitting", "https://www.sandyspringsga.gov/", "Fulton"),
  p("ga-roswell", "Roswell", "city", "GA", "Roswell Community Development", "City permitting", "https://www.roswellgov.com/", "Fulton"),
  p("ga-johns-creek", "Johns Creek", "city", "GA", "Johns Creek Community Development", "City permitting", "https://www.johnscreekga.gov/", "Fulton"),
  p("ga-fulton-county", "Fulton County", "county", "GA", "Fulton County Environment & Community Development", "County ECD", "https://www.fultoncountyga.gov/"),
  p("ga-gwinnett-county", "Gwinnett County", "county", "GA", "Gwinnett Department of Planning & Development", "County P&D", "https://www.gwinnettcounty.com/"),
  p("ga-cobb-county", "Cobb County", "county", "GA", "Cobb Community Development", "County CD", "https://www.cobbcounty.org/"),
  p("ga-dekalb-county", "DeKalb County", "county", "GA", "DeKalb Planning & Sustainability", "County planning", "https://www.dekalbcountyga.gov/"),
  // Hawaii
  p("hi-maui", "Maui County", "county", "HI", "Maui County DSA", "County DSA", "https://www.mauicounty.gov/"),
  p("hi-hawaii-county", "Hawaii County", "county", "HI", "Hawaii County Public Works Building", "County building", "https://www.hawaiicounty.gov/"),
  p("hi-kauai", "Kauai County", "county", "HI", "Kauai Planning / Building", "County planning", "https://www.kauai.gov/"),
  // Idaho
  p("id-meridian", "Meridian", "city", "ID", "Meridian Community Development", "City permitting", "https://meridiancity.org/", "Ada"),
  p("id-nampa", "Nampa", "city", "ID", "Nampa Building Department", "City permitting", "https://www.cityofnampa.us/", "Canyon"),
  p("id-idaho-falls", "Idaho Falls", "city", "ID", "Idaho Falls Building Division", "City permitting", "https://www.idahofallsidaho.gov/", "Bonneville"),
  p("id-pocatello", "Pocatello", "city", "ID", "Pocatello Building Department", "City permitting", "https://www.pocatello.gov/", "Bannock"),
  p("id-caldwell", "Caldwell", "city", "ID", "Caldwell Building Department", "City permitting", "https://www.cityofcaldwell.org/", "Canyon"),
  p("id-coeur-dalene", "Coeur d'Alene", "city", "ID", "Coeur d'Alene Building Services", "City permitting", "https://www.cdaid.org/", "Kootenai"),
  // Illinois
  p("il-aurora", "Aurora", "city", "IL", "Aurora Building & Permits", "City permitting", "https://www.aurora-il.org/", "Kane"),
  p("il-naperville", "Naperville", "city", "IL", "Naperville TED / Building", "City permitting", "https://www.naperville.il.us/", "DuPage"),
  p("il-joliet", "Joliet", "city", "IL", "Joliet Community Development", "City permitting", "https://www.joliet.gov/", "Will"),
  p("il-rockford", "Rockford", "city", "IL", "Rockford Community Development", "City permitting", "https://www.rockfordil.gov/", "Winnebago"),
  p("il-springfield", "Springfield", "city", "IL", "Springfield Building & Zoning", "City permitting", "https://www.springfield.il.us/", "Sangamon"),
  p("il-elgin", "Elgin", "city", "IL", "Elgin Community Development", "City permitting", "https://www.cityofelgin.org/", "Kane"),
  p("il-peoria", "Peoria", "city", "IL", "Peoria Community Development", "City permitting", "https://www.peoriagov.org/", "Peoria"),
  p("il-champaign", "Champaign", "city", "IL", "Champaign Neighborhood Services", "City permitting", "https://champaignil.gov/", "Champaign"),
  p("il-evanston", "Evanston", "city", "IL", "Evanston Community Development", "City permitting", "https://www.cityofevanston.org/", "Cook"),
  p("il-schaumburg", "Schaumburg", "city", "IL", "Schaumburg Community Development", "City permitting", "https://www.villageofschaumburg.com/", "Cook"),
  p("il-cook-county", "Cook County", "county", "IL", "Cook County Building & Zoning", "County B&Z", "https://www.cookcountyil.gov/", undefined, "Unincorporated Cook. Chicago is a separate AHJ."),
  p("il-dupage-county", "DuPage County", "county", "IL", "DuPage Building & Zoning", "County B&Z", "https://www.dupagecounty.gov/"),
  // Indiana
  p("in-fort-wayne", "Fort Wayne", "city", "IN", "Fort Wayne DRE / Permits", "City permitting", "https://www.cityoffortwayne.org/", "Allen"),
  p("in-evansville", "Evansville", "city", "IN", "Evansville Building Commission", "City permitting", "https://www.evansvillegov.org/", "Vanderburgh"),
  p("in-south-bend", "South Bend", "city", "IN", "South Bend Building Department", "City permitting", "https://southbendin.gov/", "St. Joseph"),
  p("in-carmel", "Carmel", "city", "IN", "Carmel Community Services / Building", "City permitting", "https://www.carmel.in.gov/", "Hamilton"),
  p("in-fishers", "Fishers", "city", "IN", "Fishers Community Development", "City permitting", "https://www.fishers.in.us/", "Hamilton"),
  p("in-bloomington", "Bloomington", "city", "IN", "Bloomington Planning & Transportation / HAND", "City permitting", "https://bloomington.in.gov/", "Monroe"),
  p("in-lafayette", "Lafayette", "city", "IN", "Lafayette Building Department", "City permitting", "https://www.lafayette.in.gov/", "Tippecanoe"),
  // Iowa
  p("ia-cedar-rapids", "Cedar Rapids", "city", "IA", "Cedar Rapids Development Services", "City permitting", "https://www.cedar-rapids.org/", "Linn"),
  p("ia-davenport", "Davenport", "city", "IA", "Davenport Community Planning & Economic Development", "City permitting", "https://www.davenportiowa.com/", "Scott"),
  p("ia-sioux-city", "Sioux City", "city", "IA", "Sioux City Community Development", "City permitting", "https://www.sioux-city.org/", "Woodbury"),
  p("ia-iowa-city", "Iowa City", "city", "IA", "Iowa City Housing & Inspection Services", "City permitting", "https://www.icgov.org/", "Johnson"),
  p("ia-waterloo", "Waterloo", "city", "IA", "Waterloo Building Inspections", "City permitting", "https://www.cityofwaterlooiowa.com/", "Black Hawk"),
  p("ia-ames", "Ames", "city", "IA", "Ames Inspections", "City permitting", "https://www.cityofames.org/", "Story"),
  p("ia-west-des-moines", "West Des Moines", "city", "IA", "West Des Moines Development Services", "City permitting", "https://www.wdm.iowa.gov/", "Polk"),
  p("ia-ankeny", "Ankeny", "city", "IA", "Ankeny Community Development", "City permitting", "https://www.ankenyiowa.gov/", "Polk"),
  // Kansas
  p("ks-overland-park", "Overland Park", "city", "KS", "Overland Park Planning & Development Services", "City permitting", "https://www.opkansas.org/", "Johnson"),
  p("ks-kansas-city", "Kansas City", "city", "KS", "UG Planning & Urban Design / Building", "UG permitting", "https://www.wycokck.org/", "Wyandotte", "Unified Government of Wyandotte County / KCK — not Kansas City, Missouri."),
  p("ks-olathe", "Olathe", "city", "KS", "Olathe Planning Division", "City permitting", "https://www.olatheks.org/", "Johnson"),
  p("ks-topeka", "Topeka", "city", "KS", "Topeka Planning & Development", "City permitting", "https://www.topeka.org/", "Shawnee"),
  p("ks-lawrence", "Lawrence", "city", "KS", "Lawrence Development Services", "City permitting", "https://lawrenceks.org/", "Douglas"),
  p("ks-shawnee", "Shawnee", "city", "KS", "Shawnee Development Services", "City permitting", "https://www.cityofshawnee.org/", "Johnson"),
  // Kentucky
  p("ky-bowling-green", "Bowling Green", "city", "KY", "Bowling Green Neighborhood & Community Services", "City permitting", "https://www.bgky.org/", "Warren"),
  p("ky-owensboro", "Owensboro", "city", "KY", "Owensboro Planning", "City permitting", "https://owensboro.org/", "Daviess"),
  p("ky-covington", "Covington", "city", "KY", "Covington Economic Development / Codes", "City permitting", "https://www.covingtonky.gov/", "Kenton"),
  p("ky-richmond", "Richmond", "city", "KY", "Richmond Planning & Zoning", "City permitting", "https://www.richmond.ky.us/", "Madison"),
  // Louisiana
  p("la-baton-rouge", "Baton Rouge", "city", "LA", "EBR Parish Development", "Parish permitting", "https://www.brla.gov/", "East Baton Rouge", "City-parish. Confirm the permit type on the parish portal."),
  p("la-shreveport", "Shreveport", "city", "LA", "Shreveport Property Standards / Permits", "City permitting", "https://www.shreveportla.gov/", "Caddo"),
  p("la-lafayette", "Lafayette", "city", "LA", "Lafayette Consolidated Government Development", "LCG permitting", "https://www.lafayettela.gov/", "Lafayette"),
  p("la-lake-charles", "Lake Charles", "city", "LA", "Lake Charles Planning", "City permitting", "https://www.cityoflakecharles.com/", "Calcasieu"),
  p("la-kenner", "Kenner", "city", "LA", "Kenner Planning / Inspections", "City permitting", "https://www.kenner.la.us/", "Jefferson"),
  p("la-bossier-city", "Bossier City", "city", "LA", "Bossier City Permits", "City permitting", "https://www.bossiercity.org/", "Bossier"),
  p("la-jefferson-parish", "Jefferson Parish", "county", "LA", "Jefferson Parish Inspection & Code", "Parish permitting", "https://www.jeffparish.gov/"),
  // Maine
  p("me-lewiston", "Lewiston", "city", "ME", "Lewiston Planning & Code", "City permitting", "https://www.lewistonmaine.gov/", "Androscoggin"),
  p("me-bangor", "Bangor", "city", "ME", "Bangor Code Enforcement", "City permitting", "https://www.bangormaine.gov/", "Penobscot"),
  p("me-south-portland", "South Portland", "city", "ME", "South Portland Planning & Development", "City permitting", "https://www.southportland.org/", "Cumberland"),
  p("me-augusta", "Augusta", "city", "ME", "Augusta Development Services", "City permitting", "https://www.augustamaine.gov/", "Kennebec"),
  // Maryland
  p("md-baltimore-county", "Baltimore County", "county", "MD", "Baltimore County Permits, Approvals & Inspections", "County PAI", "https://www.baltimorecountymd.gov/departments/permits/", undefined, "Not Baltimore City."),
  p("md-montgomery-county", "Montgomery County", "county", "MD", "Montgomery County DPS", "County DPS", "https://www.montgomerycountymd.gov/DPS/"),
  p("md-prince-georges-county", "Prince George's County", "county", "MD", "Prince George's DPIE", "County DPIE", "https://www.princegeorgescountymd.gov/"),
  p("md-anne-arundel-county", "Anne Arundel County", "county", "MD", "Anne Arundel Inspections & Permits", "County I&P", "https://www.aacounty.org/"),
  p("md-frederick", "Frederick", "city", "MD", "Frederick Planning / Building", "City permitting", "https://www.cityoffrederickmd.gov/", "Frederick"),
  p("md-rockville", "Rockville", "city", "MD", "Rockville Community Planning & Development Services", "City permitting", "https://www.rockvillemd.gov/", "Montgomery"),
  p("md-gaithersburg", "Gaithersburg", "city", "MD", "Gaithersburg Planning & Code Administration", "City permitting", "https://www.gaithersburgmd.gov/", "Montgomery"),
  p("md-annapolis", "Annapolis", "city", "MD", "Annapolis Department of Planning & Zoning", "City permitting", "https://www.annapolis.gov/", "Anne Arundel"),
  // Massachusetts
  p("ma-worcester", "Worcester", "city", "MA", "Worcester Inspectional Services", "City ISD", "https://www.worcesterma.gov/", "Worcester"),
  p("ma-springfield", "Springfield", "city", "MA", "Springfield Building Division", "City building", "https://www.springfield-ma.gov/", "Hampden"),
  p("ma-cambridge", "Cambridge", "city", "MA", "Cambridge Inspectional Services", "City ISD", "https://www.cambridgema.gov/", "Middlesex"),
  p("ma-lowell", "Lowell", "city", "MA", "Lowell Inspectional Services", "City ISD", "https://www.lowellma.gov/", "Middlesex"),
  p("ma-brockton", "Brockton", "city", "MA", "Brockton Inspectional Services", "City ISD", "https://brockton.ma.us/", "Plymouth"),
  p("ma-quincy", "Quincy", "city", "MA", "Quincy Inspectional Services", "City ISD", "https://www.quincyma.gov/", "Norfolk"),
  p("ma-lynn", "Lynn", "city", "MA", "Lynn Inspectional Services", "City ISD", "https://www.lynnma.gov/", "Essex"),
  p("ma-new-bedford", "New Bedford", "city", "MA", "New Bedford Inspectional Services", "City ISD", "https://www.newbedford-ma.gov/", "Bristol"),
  p("ma-fall-river", "Fall River", "city", "MA", "Fall River Inspectional Services", "City ISD", "https://www.fallriverma.gov/", "Bristol"),
  p("ma-newton", "Newton", "city", "MA", "Newton Inspectional Services", "City ISD", "https://www.newtonma.gov/", "Middlesex"),
  p("ma-somerville", "Somerville", "city", "MA", "Somerville Inspectional Services", "City ISD", "https://www.somervillema.gov/", "Middlesex"),
  p("ma-framingham", "Framingham", "city", "MA", "Framingham Inspectional Services", "City ISD", "https://www.framinghamma.gov/", "Middlesex"),
  // Michigan
  p("mi-grand-rapids", "Grand Rapids", "city", "MI", "Grand Rapids Development Center", "City permitting", "https://www.grandrapidsmi.gov/", "Kent"),
  p("mi-warren", "Warren", "city", "MI", "Warren Building Division", "City permitting", "https://www.cityofwarren.org/", "Macomb"),
  p("mi-sterling-heights", "Sterling Heights", "city", "MI", "Sterling Heights Building", "City permitting", "https://www.sterling-heights.net/", "Macomb"),
  p("mi-ann-arbor", "Ann Arbor", "city", "MI", "Ann Arbor Planning / Building", "City permitting", "https://www.a2gov.org/", "Washtenaw"),
  p("mi-lansing", "Lansing", "city", "MI", "Lansing Economic Development & Planning", "City permitting", "https://www.lansingmi.gov/", "Ingham"),
  p("mi-dearborn", "Dearborn", "city", "MI", "Dearborn Building & Safety", "City permitting", "https://cityofdearborn.org/", "Wayne"),
  p("mi-livonia", "Livonia", "city", "MI", "Livonia Inspection Department", "City permitting", "https://www.livonia.gov/", "Wayne"),
  p("mi-troy", "Troy", "city", "MI", "Troy Building Inspection", "City permitting", "https://www.troymi.gov/", "Oakland"),
  p("mi-flint", "Flint", "city", "MI", "Flint Planning & Development", "City permitting", "https://www.cityofflint.com/", "Genesee"),
  p("mi-kalamazoo", "Kalamazoo", "city", "MI", "Kalamazoo Community Planning & Development", "City permitting", "https://www.kalamazoocity.org/", "Kalamazoo"),
  // Minnesota
  p("mn-st-paul", "St. Paul", "city", "MN", "St. Paul DSI", "City DSI", "https://www.stpaul.gov/departments/safety-inspections", "Ramsey"),
  p("mn-rochester", "Rochester", "city", "MN", "Rochester Community Development", "City permitting", "https://www.rochestermn.gov/", "Olmsted"),
  p("mn-duluth", "Duluth", "city", "MN", "Duluth Construction Services", "City permitting", "https://duluthmn.gov/", "St. Louis"),
  p("mn-bloomington", "Bloomington", "city", "MN", "Bloomington Building & Inspection", "City permitting", "https://www.bloomingtonmn.gov/", "Hennepin"),
  p("mn-brooklyn-park", "Brooklyn Park", "city", "MN", "Brooklyn Park Community Development", "City permitting", "https://www.brooklynpark.org/", "Hennepin"),
  p("mn-plymouth", "Plymouth", "city", "MN", "Plymouth Community Development", "City permitting", "https://www.plymouthmn.gov/", "Hennepin"),
  p("mn-maple-grove", "Maple Grove", "city", "MN", "Maple Grove Community Development", "City permitting", "https://www.maplegrovemn.gov/", "Hennepin"),
  p("mn-woodbury", "Woodbury", "city", "MN", "Woodbury Building Inspections", "City permitting", "https://www.woodburymn.gov/", "Washington"),
  // Mississippi
  p("ms-gulfport", "Gulfport", "city", "MS", "Gulfport Urban Development", "City permitting", "https://www.gulfport-ms.gov/", "Harrison"),
  p("ms-southaven", "Southaven", "city", "MS", "Southaven Planning / Building", "City permitting", "https://www.southaven.org/", "DeSoto"),
  p("ms-hattiesburg", "Hattiesburg", "city", "MS", "Hattiesburg Urban Development", "City permitting", "https://www.hattiesburgms.com/", "Forrest"),
  p("ms-biloxi", "Biloxi", "city", "MS", "Biloxi Community Development", "City permitting", "https://www.biloxi.ms.us/", "Harrison"),
  p("ms-meridian", "Meridian", "city", "MS", "Meridian Community Development", "City permitting", "https://www.meridianms.org/", "Lauderdale"),
  // Missouri
  p("mo-springfield", "Springfield", "city", "MO", "Springfield Building Development Services", "City permitting", "https://www.springfieldmo.gov/", "Greene"),
  p("mo-columbia", "Columbia", "city", "MO", "Columbia Community Development", "City permitting", "https://www.como.gov/", "Boone"),
  p("mo-independence", "Independence", "city", "MO", "Independence Community Development", "City permitting", "https://www.independencemo.gov/", "Jackson"),
  p("mo-lees-summit", "Lee's Summit", "city", "MO", "Lee's Summit Development Services", "City permitting", "https://cityofls.net/", "Jackson"),
  p("mo-ofallon", "O'Fallon", "city", "MO", "O'Fallon Planning & Development", "City permitting", "https://www.ofallon.mo.us/", "St. Charles"),
  p("mo-st-joseph", "St. Joseph", "city", "MO", "St. Joseph Planning & Community Development", "City permitting", "https://www.stjoemo.info/", "Buchanan"),
  p("mo-st-charles", "St. Charles", "city", "MO", "St. Charles Community Development", "City permitting", "https://www.stcharlescitymo.gov/", "St. Charles"),
  p("mo-st-louis-county", "St. Louis County", "county", "MO", "St. Louis County Public Works", "County PW", "https://stlouiscountymo.gov/", undefined, "Not the independent City of St. Louis."),
  // Montana
  p("mt-missoula", "Missoula", "city", "MT", "Missoula Development Services", "City permitting", "https://www.ci.missoula.mt.us/", "Missoula"),
  p("mt-great-falls", "Great Falls", "city", "MT", "Great Falls Planning & Community Development", "City permitting", "https://greatfallsmt.net/", "Cascade"),
  p("mt-bozeman", "Bozeman", "city", "MT", "Bozeman Community Development", "City permitting", "https://www.bozeman.net/", "Gallatin"),
  p("mt-helena", "Helena", "city", "MT", "Helena Community Development", "City permitting", "https://www.helenamt.gov/", "Lewis and Clark"),
  p("mt-butte", "Butte", "city", "MT", "Butte-Silver Bow Building Code", "City-county permitting", "https://www.co.silverbow.mt.us/", "Silver Bow"),
  // Nebraska
  p("ne-lincoln", "Lincoln", "city", "NE", "Lincoln Building & Safety", "City permitting", "https://www.lincoln.ne.gov/", "Lancaster"),
  p("ne-bellevue", "Bellevue", "city", "NE", "Bellevue Planning / Building", "City permitting", "https://www.bellevue.net/", "Sarpy"),
  p("ne-grand-island", "Grand Island", "city", "NE", "Grand Island Building Department", "City permitting", "https://www.grand-island.com/", "Hall"),
  // Nevada
  p("nv-henderson", "Henderson", "city", "NV", "Henderson Building & Fire Safety", "City permitting", "https://www.cityofhenderson.com/", "Clark"),
  p("nv-reno", "Reno", "city", "NV", "Reno Community Development", "City permitting", "https://www.reno.gov/", "Washoe"),
  p("nv-north-las-vegas", "North Las Vegas", "city", "NV", "North Las Vegas Building & Safety", "City permitting", "https://www.cityofnorthlasvegas.com/", "Clark"),
  p("nv-sparks", "Sparks", "city", "NV", "Sparks Community Services", "City permitting", "https://www.cityofsparks.us/", "Washoe"),
  p("nv-carson-city", "Carson City", "city", "NV", "Carson City Community Development", "City-county permitting", "https://www.carson.org/"),
  p("nv-clark-county", "Clark County", "county", "NV", "Clark County Building Department", "County building", "https://www.clarkcountynv.gov/government/departments/building_department/index.php", undefined, "Unincorporated Clark. Las Vegas, Henderson, and North Las Vegas are separate AHJs."),
  // New Hampshire
  p("nh-nashua", "Nashua", "city", "NH", "Nashua Community Development", "City permitting", "https://www.nashuanh.gov/", "Hillsborough"),
  p("nh-concord", "Concord", "city", "NH", "Concord Code Administration", "City permitting", "https://www.concordnh.gov/", "Merrimack"),
  p("nh-dover", "Dover", "city", "NH", "Dover Planning / Inspections", "City permitting", "https://www.dover.nh.gov/", "Strafford"),
  p("nh-rochester", "Rochester", "city", "NH", "Rochester Building / Zoning", "City permitting", "https://www.rochesternh.gov/", "Strafford"),
  // New Jersey
  p("nj-jersey-city", "Jersey City", "city", "NJ", "Jersey City Division of Construction", "City construction", "https://www.jerseycitynj.gov/", "Hudson"),
  p("nj-paterson", "Paterson", "city", "NJ", "Paterson Community Development / Construction", "City construction", "https://www.patersonnj.gov/", "Passaic"),
  p("nj-elizabeth", "Elizabeth", "city", "NJ", "Elizabeth Construction Official", "City construction", "https://www.elizabethnj.org/", "Union"),
  p("nj-edison", "Edison", "city", "NJ", "Edison Construction / Engineering", "Township construction", "https://www.edisonnj.org/", "Middlesex"),
  p("nj-woodbridge", "Woodbridge", "city", "NJ", "Woodbridge Construction Official", "Township construction", "https://www.twp.woodbridge.nj.us/", "Middlesex"),
  p("nj-toms-river", "Toms River", "city", "NJ", "Toms River Construction / Code", "Township construction", "https://www.tomsrivertownship.com/", "Ocean"),
  p("nj-hamilton", "Hamilton", "city", "NJ", "Hamilton Construction Official", "Township construction", "https://www.hamiltonnj.com/", "Mercer"),
  p("nj-trenton", "Trenton", "city", "NJ", "Trenton Housing & Economic Development / Construction", "City construction", "https://www.trentonnj.org/", "Mercer"),
  p("nj-clifton", "Clifton", "city", "NJ", "Clifton Construction Official", "City construction", "https://www.cliftonnj.org/", "Passaic"),
  p("nj-camden", "Camden", "city", "NJ", "Camden Construction Official", "City construction", "https://www.ci.camden.nj.us/", "Camden"),
  p("nj-cherry-hill", "Cherry Hill", "city", "NJ", "Cherry Hill Construction Code", "Township construction", "https://www.chnj.gov/", "Camden"),
  p("nj-atlantic-city", "Atlantic City", "city", "NJ", "Atlantic City Construction Official", "City construction", "https://www.acnj.gov/", "Atlantic"),
  // New Mexico
  p("nm-las-cruces", "Las Cruces", "city", "NM", "Las Cruces Community Development", "City permitting", "https://www.lascruces.gov/", "Doña Ana"),
  p("nm-rio-rancho", "Rio Rancho", "city", "NM", "Rio Rancho Development Services", "City permitting", "https://rrnm.gov/", "Sandoval"),
  p("nm-santa-fe", "Santa Fe", "city", "NM", "Santa Fe Land Use / Building", "City permitting", "https://santafenm.gov/", "Santa Fe"),
  p("nm-roswell", "Roswell", "city", "NM", "Roswell Planning / Inspections", "City permitting", "https://roswell-nm.gov/", "Chaves"),
  p("nm-farmington", "Farmington", "city", "NM", "Farmington Community Development", "City permitting", "https://www.fmtn.org/", "San Juan"),
  // New York
  p("ny-rochester", "Rochester", "city", "NY", "Rochester Neighborhood & Business Development / Permits", "City permitting", "https://www.cityofrochester.gov/", "Monroe"),
  p("ny-yonkers", "Yonkers", "city", "NY", "Yonkers Housing & Buildings", "City H&B", "https://www.yonkersny.gov/", "Westchester"),
  p("ny-syracuse", "Syracuse", "city", "NY", "Syracuse Division of Code Enforcement", "City codes", "https://www.syr.gov/", "Onondaga"),
  p("ny-albany", "Albany", "city", "NY", "Albany Buildings & Regulatory Compliance", "City BRC", "https://www.albanyny.gov/", "Albany"),
  p("ny-new-rochelle", "New Rochelle", "city", "NY", "New Rochelle Bureau of Buildings", "City buildings", "https://www.newrochelleny.com/", "Westchester"),
  p("ny-mount-vernon", "Mount Vernon", "city", "NY", "Mount Vernon Buildings Department", "City buildings", "https://cmvny.com/", "Westchester"),
  p("ny-schenectady", "Schenectady", "city", "NY", "Schenectady Building Inspector", "City building", "https://www.cityofschenectady.com/", "Schenectady"),
  p("ny-utica", "Utica", "city", "NY", "Utica Codes", "City codes", "https://www.cityofutica.com/", "Oneida"),
  p("ny-white-plains", "White Plains", "city", "NY", "White Plains Building Department", "City building", "https://www.cityofwhiteplains.com/", "Westchester"),
  p("ny-hempstead", "Hempstead", "city", "NY", "Town of Hempstead Buildings", "Town buildings", "https://hempsteadny.gov/", "Nassau"),
  p("ny-brookhaven", "Brookhaven", "city", "NY", "Town of Brookhaven Building Division", "Town building", "https://www.brookhavenny.gov/", "Suffolk"),
  p("ny-islip", "Islip", "city", "NY", "Town of Islip Building Division", "Town building", "https://islipny.gov/", "Suffolk"),
  // North Carolina
  p("nc-greensboro", "Greensboro", "city", "NC", "Greensboro Planning / Inspections", "City permitting", "https://www.greensboro-nc.gov/", "Guilford"),
  p("nc-durham", "Durham", "city", "NC", "Durham City-County Inspections", "City-county inspections", "https://www.durhamnc.gov/", "Durham"),
  p("nc-winston-salem", "Winston-Salem", "city", "NC", "Winston-Salem / Forsyth Inspections", "City-county inspections", "https://www.cityofws.org/", "Forsyth"),
  p("nc-fayetteville", "Fayetteville", "city", "NC", "Fayetteville Development Services", "City permitting", "https://www.fayettevillenc.gov/", "Cumberland"),
  p("nc-cary", "Cary", "city", "NC", "Cary Development Services", "Town permitting", "https://www.carync.gov/", "Wake"),
  p("nc-wilmington", "Wilmington", "city", "NC", "Wilmington Development Services", "City permitting", "https://www.wilmingtonnc.gov/", "New Hanover"),
  p("nc-high-point", "High Point", "city", "NC", "High Point Inspections", "City inspections", "https://www.highpointnc.gov/", "Guilford"),
  p("nc-concord", "Concord", "city", "NC", "Concord Planning & Neighborhood Development", "City permitting", "https://www.concordnc.gov/", "Cabarrus"),
  p("nc-asheville", "Asheville", "city", "NC", "Asheville Development Services", "City permitting", "https://www.ashevillenc.gov/", "Buncombe"),
  p("nc-greenville", "Greenville", "city", "NC", "Greenville Community Development", "City permitting", "https://www.greenvillenc.gov/", "Pitt"),
  p("nc-jacksonville", "Jacksonville", "city", "NC", "Jacksonville Planning / Inspections", "City permitting", "https://jacksonvillenc.gov/", "Onslow"),
  // North Dakota
  p("nd-bismarck", "Bismarck", "city", "ND", "Bismarck Community Development", "City permitting", "https://www.bismarcknd.gov/", "Burleigh"),
  p("nd-grand-forks", "Grand Forks", "city", "ND", "Grand Forks Inspections", "City inspections", "https://www.grandforksgov.com/", "Grand Forks"),
  p("nd-minot", "Minot", "city", "ND", "Minot Inspections", "City inspections", "https://www.minotnd.gov/", "Ward"),
  // Ohio
  p("oh-cincinnati", "Cincinnati", "city", "OH", "Cincinnati Buildings & Inspections", "City B&I", "https://www.cincinnati-oh.gov/", "Hamilton"),
  p("oh-toledo", "Toledo", "city", "OH", "Toledo Division of Building Inspection", "City building", "https://toledo.oh.gov/", "Lucas"),
  p("oh-akron", "Akron", "city", "OH", "Akron Planning & Urban Development", "City permitting", "https://www.akronohio.gov/", "Summit"),
  p("oh-dayton", "Dayton", "city", "OH", "Dayton Building Services", "City building", "https://www.daytonohio.gov/", "Montgomery"),
  p("oh-parma", "Parma", "city", "OH", "Parma Building Department", "City building", "https://www.cityofparma-oh.gov/", "Cuyahoga"),
  p("oh-canton", "Canton", "city", "OH", "Canton Building Department", "City building", "https://www.cantonohio.gov/", "Stark"),
  p("oh-youngstown", "Youngstown", "city", "OH", "Youngstown Building Department", "City building", "https://youngstownohio.gov/", "Mahoning"),
  p("oh-hamilton", "Hamilton", "city", "OH", "Hamilton Building Department", "City building", "https://www.hamilton-oh.gov/", "Butler"),
  p("oh-springfield", "Springfield", "city", "OH", "Springfield Building / Zoning", "City building", "https://www.springfieldohio.gov/", "Clark"),
  // Oklahoma
  p("ok-tulsa", "Tulsa", "city", "OK", "Tulsa Development Services", "City permitting", "https://www.cityoftulsa.org/", "Tulsa"),
  p("ok-norman", "Norman", "city", "OK", "Norman Planning / Development", "City permitting", "https://www.normanok.gov/", "Cleveland"),
  p("ok-broken-arrow", "Broken Arrow", "city", "OK", "Broken Arrow Development Services", "City permitting", "https://www.brokenarrowok.gov/", "Tulsa"),
  p("ok-edmond", "Edmond", "city", "OK", "Edmond Planning / Building", "City permitting", "https://www.edmondok.gov/", "Oklahoma"),
  p("ok-lawton", "Lawton", "city", "OK", "Lawton Planning / Inspections", "City permitting", "https://www.lawtonok.gov/", "Comanche"),
  p("ok-moore", "Moore", "city", "OK", "Moore Community Development", "City permitting", "https://www.cityofmoore.com/", "Cleveland"),
  // Oregon
  p("or-eugene", "Eugene", "city", "OR", "Eugene Planning & Development", "City permitting", "https://www.eugene-or.gov/", "Lane"),
  p("or-salem", "Salem", "city", "OR", "Salem Community Development / Permits", "City permitting", "https://www.cityofsalem.net/", "Marion"),
  p("or-gresham", "Gresham", "city", "OR", "Gresham Urban Design & Planning", "City permitting", "https://greshamoregon.gov/", "Multnomah"),
  p("or-hillsboro", "Hillsboro", "city", "OR", "Hillsboro Planning / Building", "City permitting", "https://www.hillsboro-oregon.gov/", "Washington"),
  p("or-bend", "Bend", "city", "OR", "Bend Community Development", "City permitting", "https://www.bendoregon.gov/", "Deschutes"),
  p("or-beaverton", "Beaverton", "city", "OR", "Beaverton Community Development", "City permitting", "https://www.beavertonoregon.gov/", "Washington"),
  p("or-medford", "Medford", "city", "OR", "Medford Building Safety", "City permitting", "https://www.medfordoregon.gov/", "Jackson"),
  p("or-springfield", "Springfield", "city", "OR", "Springfield Development & Public Works", "City permitting", "https://www.springfield-or.gov/", "Lane"),
  // Pennsylvania
  p("pa-allentown", "Allentown", "city", "PA", "Allentown Building Standards & Safety", "City permitting", "https://www.allentownpa.gov/", "Lehigh"),
  p("pa-reading", "Reading", "city", "PA", "Reading Community Development", "City permitting", "https://www.readingpa.gov/", "Berks"),
  p("pa-erie", "Erie", "city", "PA", "Erie Code Enforcement", "City codes", "https://cityof.erie.pa.us/", "Erie"),
  p("pa-scranton", "Scranton", "city", "PA", "Scranton Licensing / Inspections", "City L&I", "https://scrantonpa.gov/", "Lackawanna"),
  p("pa-bethlehem", "Bethlehem", "city", "PA", "Bethlehem Community & Economic Development", "City permitting", "https://www.bethlehem-pa.gov/", "Northampton"),
  p("pa-lancaster", "Lancaster", "city", "PA", "Lancaster Building / Zoning", "City permitting", "https://cityoflancasterpa.gov/", "Lancaster"),
  p("pa-harrisburg", "Harrisburg", "city", "PA", "Harrisburg Building / Housing", "City permitting", "https://harrisburgpa.gov/", "Dauphin"),
  p("pa-york", "York", "city", "PA", "York Permits / Inspections", "City permitting", "https://www.yorkcity.org/", "York"),
  p("pa-allegheny-county", "Allegheny County", "county", "PA", "Allegheny County Economic Development / Permits", "County permitting", "https://www.alleghenycounty.us/", undefined, "Municipalities inside the county often issue their own permits."),
  // Rhode Island
  p("ri-warwick", "Warwick", "city", "RI", "Warwick Building Inspection", "City building", "https://www.warwickri.gov/", "Kent"),
  p("ri-cranston", "Cranston", "city", "RI", "Cranston Building Inspections", "City building", "https://www.cranstonri.gov/", "Providence"),
  p("ri-pawtucket", "Pawtucket", "city", "RI", "Pawtucket Zoning & Code Enforcement", "City building", "https://www.pawtucketri.gov/", "Providence"),
  p("ri-east-providence", "East Providence", "city", "RI", "East Providence Building Inspection", "City building", "https://eastprovidenceri.gov/", "Providence"),
  // South Carolina
  p("sc-columbia", "Columbia", "city", "SC", "Columbia Development Services", "City permitting", "https://columbiasc.gov/", "Richland"),
  p("sc-north-charleston", "North Charleston", "city", "SC", "North Charleston Planning / Building", "City permitting", "https://www.northcharleston.org/", "Charleston"),
  p("sc-mount-pleasant", "Mount Pleasant", "city", "SC", "Mount Pleasant Planning & Development", "Town permitting", "https://www.tompsc.com/", "Charleston"),
  p("sc-rock-hill", "Rock Hill", "city", "SC", "Rock Hill Planning & Development", "City permitting", "https://www.cityofrockhill.com/", "York"),
  p("sc-greenville", "Greenville", "city", "SC", "Greenville Building Codes / Permits", "City permitting", "https://www.greenvillesc.gov/", "Greenville"),
  p("sc-summerville", "Summerville", "city", "SC", "Summerville Planning / Building", "Town permitting", "https://www.summervillesc.gov/", "Dorchester"),
  p("sc-spartanburg", "Spartanburg", "city", "SC", "Spartanburg Planning / Building", "City permitting", "https://www.cityofspartanburg.org/", "Spartanburg"),
  // South Dakota
  p("sd-rapid-city", "Rapid City", "city", "SD", "Rapid City Community Development", "City permitting", "https://www.rcgov.org/", "Pennington"),
  p("sd-aberdeen", "Aberdeen", "city", "SD", "Aberdeen Planning / Inspections", "City permitting", "https://www.aberdeen.sd.us/", "Brown"),
  p("sd-brookings", "Brookings", "city", "SD", "Brookings Community Development", "City permitting", "https://www.cityofbrookings.org/", "Brookings"),
  // Tennessee
  p("tn-knoxville", "Knoxville", "city", "TN", "Knoxville Plans Review & Inspections", "City permitting", "https://www.knoxvilletn.gov/", "Knox"),
  p("tn-chattanooga", "Chattanooga", "city", "TN", "Chattanooga Land Development Office", "City LDO", "https://chattanooga.gov/", "Hamilton"),
  p("tn-clarksville", "Clarksville", "city", "TN", "Clarksville Building & Codes", "City codes", "https://www.cityofclarksville.com/", "Montgomery"),
  p("tn-murfreesboro", "Murfreesboro", "city", "TN", "Murfreesboro Building & Codes", "City codes", "https://www.murfreesborotn.gov/", "Rutherford"),
  p("tn-franklin", "Franklin", "city", "TN", "Franklin Building / Planning", "City permitting", "https://www.franklintn.gov/", "Williamson"),
  p("tn-jackson", "Jackson", "city", "TN", "Jackson Planning / Codes", "City codes", "https://www.jacksontn.gov/", "Madison"),
  p("tn-johnson-city", "Johnson City", "city", "TN", "Johnson City Development Services", "City permitting", "https://www.johnsoncitytn.org/", "Washington"),
  // Texas — remaining large cities + counties
  p("tx-el-paso", "El Paso", "city", "TX", "El Paso Planning & Inspections", "City permitting", "https://www.elpasotexas.gov/", "El Paso"),
  p("tx-arlington", "Arlington", "city", "TX", "Arlington Planning & Development Services", "City permitting", "https://www.arlingtontx.gov/", "Tarrant"),
  p("tx-corpus-christi", "Corpus Christi", "city", "TX", "Corpus Christi Development Services", "City permitting", "https://www.cctexas.com/", "Nueces"),
  p("tx-plano", "Plano", "city", "TX", "Plano Building Inspections", "City permitting", "https://www.plano.gov/", "Collin"),
  p("tx-laredo", "Laredo", "city", "TX", "Laredo Building Development Services", "City permitting", "https://www.cityoflaredo.com/", "Webb"),
  p("tx-lubbock", "Lubbock", "city", "TX", "Lubbock Building Safety", "City permitting", "https://ci.lubbock.tx.us/", "Lubbock"),
  p("tx-garland", "Garland", "city", "TX", "Garland Building Inspection", "City permitting", "https://www.garlandtx.gov/", "Dallas"),
  p("tx-irving", "Irving", "city", "TX", "Irving Inspections", "City permitting", "https://www.cityofirving.org/", "Dallas"),
  p("tx-amarillo", "Amarillo", "city", "TX", "Amarillo Planning / Building", "City permitting", "https://www.amarillo.gov/", "Potter"),
  p("tx-grand-prairie", "Grand Prairie", "city", "TX", "Grand Prairie Planning / Building", "City permitting", "https://www.gptx.org/", "Dallas"),
  p("tx-brownsville", "Brownsville", "city", "TX", "Brownsville Planning / Building", "City permitting", "https://www.brownsvilletx.gov/", "Cameron"),
  p("tx-mckinney", "McKinney", "city", "TX", "McKinney Development Services", "City permitting", "https://www.mckinneytexas.org/", "Collin"),
  p("tx-frisco", "Frisco", "city", "TX", "Frisco Development Services", "City permitting", "https://www.friscotexas.gov/", "Collin"),
  p("tx-pasadena", "Pasadena", "city", "TX", "Pasadena Planning / Building", "City permitting", "https://www.pasadenatx.gov/", "Harris"),
  p("tx-mesquite", "Mesquite", "city", "TX", "Mesquite Planning / Building", "City permitting", "https://www.cityofmesquite.com/", "Dallas"),
  p("tx-mcallen", "McAllen", "city", "TX", "McAllen Planning / Building", "City permitting", "https://www.mcallen.net/", "Hidalgo"),
  p("tx-killeen", "Killeen", "city", "TX", "Killeen Planning / Building", "City permitting", "https://www.killeentexas.gov/", "Bell"),
  p("tx-waco", "Waco", "city", "TX", "Waco Inspection Services", "City permitting", "https://www.waco-texas.com/", "McLennan"),
  p("tx-denton", "Denton", "city", "TX", "Denton Development Services", "City permitting", "https://www.cityofdenton.com/", "Denton"),
  p("tx-midland", "Midland", "city", "TX", "Midland Development Services", "City permitting", "https://www.midlandtexas.gov/", "Midland"),
  p("tx-abilene", "Abilene", "city", "TX", "Abilene Planning / Building", "City permitting", "https://www.abilenetx.gov/", "Taylor"),
  p("tx-beaumont", "Beaumont", "city", "TX", "Beaumont Planning / Building", "City permitting", "https://beaumonttexas.gov/", "Jefferson"),
  p("tx-round-rock", "Round Rock", "city", "TX", "Round Rock Planning / Development", "City permitting", "https://www.roundrocktexas.gov/", "Williamson"),
  p("tx-odessa", "Odessa", "city", "TX", "Odessa Development Services", "City permitting", "https://www.odessa-tx.gov/", "Ector"),
  p("tx-college-station", "College Station", "city", "TX", "College Station Planning & Development", "City permitting", "https://www.cstx.gov/", "Brazos"),
  p("tx-tyler", "Tyler", "city", "TX", "Tyler Development Services", "City permitting", "https://www.cityoftyler.org/", "Smith"),
  p("tx-pearland", "Pearland", "city", "TX", "Pearland Community Development", "City permitting", "https://www.pearlandtx.gov/", "Brazoria"),
  p("tx-sugar-land", "Sugar Land", "city", "TX", "Sugar Land Development Services", "City permitting", "https://www.sugarlandtx.gov/", "Fort Bend"),
  p("tx-harris-county", "Harris County", "county", "TX", "Harris County Engineering / Permits", "County engineering", "https://www.eng.hctx.net/", undefined, "Unincorporated Harris. Houston is a separate AHJ."),
  p("tx-dallas-county", "Dallas County", "county", "TX", "Dallas County Public Works / Unincorporated permits", "County PW", "https://www.dallascounty.org/"),
  p("tx-tarrant-county", "Tarrant County", "county", "TX", "Tarrant County Fire Marshal / Development", "County development", "https://www.tarrantcountytx.gov/"),
  p("tx-travis-county", "Travis County", "county", "TX", "Travis County Transportation & Natural Resources", "County TNR", "https://www.traviscountytx.gov/tnr"),
  p("tx-bexar-county", "Bexar County", "county", "TX", "Bexar County Public Works", "County PW", "https://www.bexar.org/"),
  // Utah
  p("ut-west-valley", "West Valley City", "city", "UT", "West Valley Building / Planning", "City permitting", "https://www.wvc-ut.gov/", "Salt Lake"),
  p("ut-provo", "Provo", "city", "UT", "Provo Community Development", "City permitting", "https://www.provo.gov/", "Utah"),
  p("ut-west-jordan", "West Jordan", "city", "UT", "West Jordan Building / Planning", "City permitting", "https://www.westjordan.utah.gov/", "Salt Lake"),
  p("ut-orem", "Orem", "city", "UT", "Orem Development Services", "City permitting", "https://orem.gov/", "Utah"),
  p("ut-sandy", "Sandy", "city", "UT", "Sandy Community Development", "City permitting", "https://sandy.utah.gov/", "Salt Lake"),
  p("ut-ogden", "Ogden", "city", "UT", "Ogden Community Development", "City permitting", "https://www.ogdencity.com/", "Weber"),
  p("ut-st-george", "St. George", "city", "UT", "St. George Community Development", "City permitting", "https://www.sgcity.org/", "Washington"),
  p("ut-layton", "Layton", "city", "UT", "Layton Community Development", "City permitting", "https://www.laytoncity.org/", "Davis"),
  p("ut-south-jordan", "South Jordan", "city", "UT", "South Jordan Building / Planning", "City permitting", "https://www.sjc.utah.gov/", "Salt Lake"),
  p("ut-lehi", "Lehi", "city", "UT", "Lehi Community Development", "City permitting", "https://www.lehi-ut.gov/", "Utah"),
  // Vermont
  p("vt-south-burlington", "South Burlington", "city", "VT", "South Burlington Planning / Zoning", "City permitting", "https://www.southburlingtonvt.gov/", "Chittenden"),
  p("vt-rutland", "Rutland", "city", "VT", "Rutland Building / Zoning", "City permitting", "https://www.rutlandcity.org/", "Rutland"),
  p("vt-montpelier", "Montpelier", "city", "VT", "Montpelier Planning / Zoning", "City permitting", "https://www.montpelier-vt.org/", "Washington"),
  // Virginia
  p("va-norfolk", "Norfolk", "city", "VA", "Norfolk Planning / Building", "City permitting", "https://www.norfolk.gov/", undefined, "Independent city."),
  p("va-chesapeake", "Chesapeake", "city", "VA", "Chesapeake Development & Permits", "City permitting", "https://www.cityofchesapeake.net/", undefined, "Independent city."),
  p("va-arlington", "Arlington County", "county", "VA", "Arlington Inspection Services", "County inspections", "https://www.arlingtonva.us/"),
  p("va-fairfax-county", "Fairfax County", "county", "VA", "Fairfax Land Development Services", "County LDS", "https://www.fairfaxcounty.gov/landdevelopment/"),
  p("va-alexandria", "Alexandria", "city", "VA", "Alexandria Code Administration", "City permitting", "https://www.alexandriava.gov/", undefined, "Independent city."),
  p("va-newport-news", "Newport News", "city", "VA", "Newport News Codes Compliance", "City codes", "https://www.nnva.gov/"),
  p("va-hampton", "Hampton", "city", "VA", "Hampton Community Development", "City permitting", "https://hampton.gov/"),
  p("va-roanoke", "Roanoke", "city", "VA", "Roanoke Building Inspections", "City inspections", "https://www.roanokeva.gov/"),
  p("va-lynchburg", "Lynchburg", "city", "VA", "Lynchburg Community Development", "City permitting", "https://www.lynchburgva.gov/"),
  p("va-suffolk", "Suffolk", "city", "VA", "Suffolk Community Development", "City permitting", "https://www.suffolkva.us/"),
  p("va-portsmouth", "Portsmouth", "city", "VA", "Portsmouth Permits & Inspections", "City permitting", "https://www.portsmouthva.gov/"),
  p("va-prince-william-county", "Prince William County", "county", "VA", "Prince William Development Services", "County DS", "https://www.pwcva.gov/"),
  p("va-loudoun-county", "Loudoun County", "county", "VA", "Loudoun Building & Development", "County B&D", "https://www.loudoun.gov/"),
  // Washington
  p("wa-spokane", "Spokane", "city", "WA", "Spokane Development Services", "City permitting", "https://my.spokanecity.org/", "Spokane"),
  p("wa-tacoma", "Tacoma", "city", "WA", "Tacoma Planning & Development Services", "City PDS", "https://www.cityoftacoma.org/", "Pierce"),
  p("wa-vancouver", "Vancouver", "city", "WA", "Vancouver Community Development", "City permitting", "https://www.cityofvancouver.us/", "Clark"),
  p("wa-bellevue", "Bellevue", "city", "WA", "Bellevue Development Services", "City permitting", "https://bellevuewa.gov/", "King"),
  p("wa-kent", "Kent", "city", "WA", "Kent Economic & Community Development", "City permitting", "https://www.kentwa.gov/", "King"),
  p("wa-everett", "Everett", "city", "WA", "Everett Planning / Permitting", "City permitting", "https://www.everettwa.gov/", "Snohomish"),
  p("wa-renton", "Renton", "city", "WA", "Renton Community & Economic Development", "City permitting", "https://www.rentonwa.gov/", "King"),
  p("wa-spokane-valley", "Spokane Valley", "city", "WA", "Spokane Valley Community Development", "City permitting", "https://www.spokanevalleywa.gov/", "Spokane"),
  p("wa-federal-way", "Federal Way", "city", "WA", "Federal Way Community Development", "City permitting", "https://www.federalwaywa.gov/", "King"),
  p("wa-yakima", "Yakima", "city", "WA", "Yakima Codes / Planning", "City permitting", "https://www.yakimawa.gov/", "Yakima"),
  p("wa-bellingham", "Bellingham", "city", "WA", "Bellingham Planning & Community Development", "City permitting", "https://cob.org/", "Whatcom"),
  p("wa-kirkland", "Kirkland", "city", "WA", "Kirkland Planning & Building", "City permitting", "https://www.kirklandwa.gov/", "King"),
  p("wa-king-county", "King County", "county", "WA", "King County Permitting", "County permitting", "https://kingcounty.gov/depts/permitting.aspx", undefined, "Unincorporated King. Seattle is a separate AHJ."),
  p("wa-pierce-county", "Pierce County", "county", "WA", "Pierce County Planning & Public Works", "County PPW", "https://www.piercecountywa.gov/"),
  p("wa-snohomish-county", "Snohomish County", "county", "WA", "Snohomish County PDS", "County PDS", "https://snohomishcountywa.gov/"),
  // West Virginia (was missing)
  p("wv-charleston", "Charleston", "city", "WV", "Charleston Building Commission", "City building", "https://www.charlestonwv.gov/", "Kanawha"),
  p("wv-huntington", "Huntington", "city", "WV", "Huntington Planning / Inspections", "City permitting", "https://www.cityofhuntington.com/", "Cabell"),
  p("wv-morgantown", "Morgantown", "city", "WV", "Morgantown Planning / Building", "City permitting", "https://www.morgantownwv.gov/", "Monongalia"),
  p("wv-parkersburg", "Parkersburg", "city", "WV", "Parkersburg Development / Building", "City permitting", "https://parkersburgcity.com/", "Wood"),
  p("wv-wheeling", "Wheeling", "city", "WV", "Wheeling Building Inspection", "City building", "https://www.wheelingwv.gov/", "Ohio"),
  // Wisconsin
  p("wi-madison", "Madison", "city", "WI", "Madison Building Inspection", "City inspection", "https://www.cityofmadison.com/", "Dane"),
  p("wi-green-bay", "Green Bay", "city", "WI", "Green Bay Inspection Services", "City inspection", "https://greenbaywi.gov/", "Brown"),
  p("wi-kenosha", "Kenosha", "city", "WI", "Kenosha Department of City Development", "City development", "https://www.kenosha.org/", "Kenosha"),
  p("wi-racine", "Racine", "city", "WI", "Racine Development / Building", "City permitting", "https://www.cityofracine.org/", "Racine"),
  p("wi-appleton", "Appleton", "city", "WI", "Appleton Inspections", "City inspections", "https://www.appleton.org/", "Outagamie"),
  p("wi-waukesha", "Waukesha", "city", "WI", "Waukesha Community Development / Building", "City permitting", "https://www.waukesha-wi.gov/", "Waukesha"),
  p("wi-eau-claire", "Eau Claire", "city", "WI", "Eau Claire Inspections", "City inspections", "https://www.eauclairewi.gov/", "Eau Claire"),
  p("wi-oshkosh", "Oshkosh", "city", "WI", "Oshkosh Inspections", "City inspections", "https://www.oshkoshwi.gov/", "Winnebago"),
  // Wyoming
  p("wy-casper", "Casper", "city", "WY", "Casper Community Development", "City permitting", "https://casperwy.gov/", "Natrona"),
  p("wy-laramie", "Laramie", "city", "WY", "Laramie Planning / Building", "City permitting", "https://www.cityoflaramie.org/", "Albany"),
  p("wy-gillette", "Gillette", "city", "WY", "Gillette Community Development", "City permitting", "https://www.gillettewy.gov/", "Campbell"),
  p("wy-rock-springs", "Rock Springs", "city", "WY", "Rock Springs Planning / Building", "City permitting", "https://www.rswy.net/", "Sweetwater"),
  p("wy-sheridan", "Sheridan", "city", "WY", "Sheridan Planning / Building", "City permitting", "https://www.sheridanwy.gov/", "Sheridan"),
];
